### ISSUE TITLE
Subject and MonoTypeOperatorFunction has no exported member

### ISSUE THREAD

**Issue by slashinski** [smnbbrv/ng2-rx-collector#2]
rxjs update doesn't have the MonoTypeOperatorFunction in the path of rxjs/interfaces anymore.  This needs to be updated to just the root of rxjs, same goes for Subject.

I ran into this error when refactoring my code to use the untilDestroyed:
"node_modules/rxjs/interfaces"' has no exported member 'MonoTypeOperatorFunction'."
Can't resolve 'rxjs/Subject'

untilDestroyed.d.ts should be updated to reflect this for the import:
import { MonoTypeOperatorFunction, Subject } from 'rxjs';

**Comment by slashinski** [comment]
This needs to be updated to rxjs 6 and Angular 6.  Until then this issue is valid but would be corrected with the updates.

**Comment by smnbbrv** [comment]
hi, please check @3.0.0
